const PDFDocument = require('pdfkit');
const fs = require('fs');

const doc = new PDFDocument({ margin: 50 });

doc.pipe(fs.createWriteStream('demoWork.pdf'));

// Title
doc.fontSize(24).text('WAVE INIT LMS - Full Workflow Documentation', { align: 'center' });
doc.moveDown();
doc.fontSize(12).text('This document outlines the complete workflow and interactions within the WAVE INIT Learning Management System across all user roles: Admin, Trainer, and Participant.', { align: 'justify' });
doc.moveDown(2);

// 1. Admin Workflow
doc.fontSize(18).text('1. Administrator Workflow', { underline: true });
doc.moveDown();
doc.fontSize(12)
   .text('• Initialization:', { continued: true, bold: true }).text(' Logs into the Admin Dashboard.', { bold: false })
   .text('• Manage Trainings:', { continued: true, bold: true }).text(' Creates new training sessions, assigns a Trainer, and sets the schedule and capacity.', { bold: false })
   .text('• Monitor Trainers:', { continued: true, bold: true }).text(' Views the complete list of registered Trainers, their extended profiles (qualifications, experience, and uploaded photos), and their performance.', { bold: false })
   .text('• Feedback Analysis:', { continued: true, bold: true }).text(' Accesses system-wide feedback submitted by participants to monitor training effectiveness.', { bold: false });
doc.moveDown(2);

// 2. Trainer Workflow
doc.fontSize(18).text('2. Trainer Workflow', { underline: true });
doc.moveDown();
doc.fontSize(12)
   .text('• Initialization:', { continued: true, bold: true }).text(' Logs into the Trainer Dashboard.', { bold: false })
   .text('• Profile Management:', { continued: true, bold: true }).text(' Navigates to their profile to update their phone number, date of birth, qualifications, and experience. Uploads a profile photo securely.', { bold: false })
   .text('• View Assignments:', { continued: true, bold: true }).text(' Checks assigned trainings and views the list of enrolled participants for each session.', { bold: false })
   .text('• Review Feedback:', { continued: true, bold: true }).text(' Reads feedback specific to the trainings they conducted, noting ratings and comments from participants.', { bold: false })
   .text('• Account Security:', { continued: true, bold: true }).text(' Updates their password if necessary via the integrated Change Password modal.', { bold: false });
doc.moveDown(2);

// 3. Participant Workflow
doc.fontSize(18).text('3. Participant Workflow', { underline: true });
doc.moveDown();
doc.fontSize(12)
   .text('• Initialization:', { continued: true, bold: true }).text(' Logs into the Participant Dashboard.', { bold: false })
   .text('• Browse & Enroll:', { continued: true, bold: true }).text(' Views available trainings, checks seat availability, and enrolls in desired sessions.', { bold: false })
   .text('• Participate:', { continued: true, bold: true }).text(' Attends the scheduled training sessions.', { bold: false })
   .text('• Submit Feedback:', { continued: true, bold: true }).text(' After completion, submits comprehensive feedback (rating the trainer, rating the subject, and leaving comments) for the training. Can choose to submit anonymously.', { bold: false });
doc.moveDown(2);

// Technical Architecture & Security
doc.fontSize(18).text('4. Technical Architecture & Data Flow', { underline: true });
doc.moveDown();
doc.fontSize(12)
   .text('• API Security:', { continued: true, bold: true }).text(' All endpoints are protected by JWT-based authentication and role-based middleware ensuring strict separation of duties.', { bold: false })
   .text('• Form Handling:', { continued: true, bold: true }).text(' Complex operations like Profile Updates utilize multipart/form-data to safely process text data alongside image files.', { bold: false })
   .text('• Database Schema:', { continued: true, bold: true }).text(' Managed via Sequelize ORM with clear relations between Users, TrainerProfiles, Trainings, Enrollments, and Feedbacks.', { bold: false });

doc.moveDown(3);
doc.fontSize(10).fillColor('gray').text('Generated by Antigravity AI Assistant', { align: 'center' });

doc.end();

console.log('Successfully generated demoWork.pdf');
